language: node_js
node_js:
  - "0.10"
  - "0.11"
after_script: NODE_ENV=test ./node_modules/istanbul/lib/cli.js cover ./node_modules/jasmine/bin/jasmine.js --report lcovonly --  spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
